"""Updated DB schema

Revision ID: 07240cffb100
Revises: 09e166916423
Create Date: 2025-08-19 11:08:09.380395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07240cffb100'
down_revision: Union[str, Sequence[str], None] = '09e166916423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_keys')
    op.drop_table('developers')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tech_stack', sa.String(), nullable=False))
    op.add_column('users', sa.Column('github_status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('joined_on', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('active_projects', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('otp', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp')
    op.drop_column('users', 'active_projects')
    op.drop_column('users', 'joined_on')
    op.drop_column('users', 'github_status')
    op.drop_column('users', 'tech_stack')
    op.drop_column('users', 'phone')
    op.create_table('developers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tech_stack', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('github_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('joined_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active_projects', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('developers_pkey'))
    )
    op.create_table('user_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_keys_pkey'))
    )
    # ### end Alembic commands ###
