"""Made few fields nullable

Revision ID: 5728d1523af3
Revises: 07240cffb100
Create Date: 2025-08-19 11:53:06.663852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5728d1523af3'
down_revision: Union[str, Sequence[str], None] = '07240cffb100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tech_stack',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'github_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'joined_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'active_projects',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'otp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'active_projects',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'joined_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'github_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'tech_stack',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
